Repository bandungdevcom/bandungdev.com, pull requests merged in 2024-01, with the labels that each got.

#36 Add user settings to change avatar
  app/components/shared/avatar-change-field.tsx
  app/components/shared/avatar-uploader.tsx
  app/components/shared/form-change-links.tsx
  app/models/user.server.ts
  app/routes/user.settings.tsx
  app/schemas/user.ts
  app/types/json.ts
Labels: enhancement

#49 Modify db query to user upsert
  app/models/user.server.ts
Labels: bug, enhancement

#42 Add cover image event field and complete info event list
  app/components/contents/events.tsx
  app/components/shared/avatar-change-field.tsx
  app/components/shared/event-cover-change-field.tsx
  app/components/shared/event-detail-form.tsx
  app/components/shared/event-item.tsx
  app/components/shared/uploader.tsx
  app/models/admin-event.server.ts
  app/models/event.server.ts
  app/routes/_index.tsx
  app/routes/admin.events.$eventId.tsx
  app/routes/events._index.tsx
  app/schemas/event.ts
Labels: enhancement

#52 Add JobType model
  prisma/schema.prisma
Labels: enhancement

#55 fix event location url display
  app/routes/events.$eventSlug.tsx
Labels: bug
